# ---------- Base Stage ----------
FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./

# ---------- Dev Stage ----------
FROM base AS dev
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host"]

# ---------- Build Stage ----------
FROM base AS build
RUN npm ci
COPY . .
RUN npm run build

# ---------- Production Stage ----------
FROM nginx:1.27-alpine AS prod
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
